name: TestFlight build

on:
  workflow_dispatch:
    inputs:
      build-number:
        description: Build number
        required: true
      github-release-version:
        description: Github release version
        default: ''
        required: false

jobs:
  testflight-build:
    name: Create new iOS & Android builds and upload them via Testflight
    runs-on: macos-latest
    environment: fastlane
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Prepare changelog
        id: changelog
        run: echo "##[set-output name=log;]$(git log --pretty=format:'%s' origin/master..origin/$(echo ${GITHUB_REF#refs/heads/}))"

      - name: Install SSH key to get acces to repository with Certificates and Provisioning profiles
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Write secrets to google-services.json
        run: |
          cat << EOF > ./android/app/google-services.json
          ${{ secrets.FIREBASE_GOOGLE_SERVICE_ANDROID }}
          EOF

      - name: Write secrets to GoogleService-Info.plist
        run: |
          cat << EOF > ./ios/GoogleService-Info.plist
          ${{ secrets.FIREBASE_GOOGLE_SERVICE_IOS }}
          EOF

      - name: Create .env file
        run: |
          cat << EOF > .env
          READ_ONLY_SIGNER_PUBLIC_KEY=${{ secrets.READ_ONLY_SIGNER_PUBLIC_KEY }}
          READ_ONLY_SIGNER_PUBLIC_KEY_HASH=${{ secrets.READ_ONLY_SIGNER_PUBLIC_KEY_HASH }}
          TEMPLE_WALLET_API=${{ secrets.TEMPLE_WALLET_API }}
          SEGMENT_ANALYTICS_KEY=${{ secrets.SEGMENT_ANALYTICS_KEY }}
          TEMPLE_WALLET_EXOLIX_API_KEY=${{ secrets.TEMPLE_WALLET_EXOLIX_API_KEY }}
          TEMPLE_WALLET_EVERSTAKE_API_KEY=${{ secrets.TEMPLE_WALLET_EVERSTAKE_API_KEY }}
          TEMPLE_WALLET_EVERSTAKE_LINK_ID=${{ secrets.TEMPLE_WALLET_EVERSTAKE_LINK_ID }}
          TEMPLE_WALLET_UTORG_SID=${{ secrets.TEMPLE_WALLET_UTORG_SID }}
          EOF

      - name: Install Android Gemfile dependencies
        run: cd android && bundle install

      - name: Build Android & Distribute to Google Play Console
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          cd android && ./decrypt_script.sh
          yarn android:test-flight
        env:
          BUILD_NUMBER: ${{ github.event.inputs.build-number }}
          GOOGLE_PLAY_AUTHKEY: ${{ secrets.GOOGLE_PLAY_AUTHKEY }}
          KEYSTORE_KEY: ${{ secrets.KEYSTORE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: Create Github release
        if: ${{ github.event.inputs.github-release-version != '' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.github-release-version }}(${{ github.event.inputs.build-number }})
          prerelease: false
          files: |
            android/app/build/outputs/apk/release/app-release.apk

      - name: Install iOS Gemfile dependencies
        run: cd ios && bundle install

      - name: Install Pods
        run: yarn ios:pods

      - name: Build iOS & Distribute to Testflight
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          cd ios && ./decrypt_script.sh
          yarn ios:test-flight
        env:
          BUILD_NUMBER: ${{ github.event.inputs.build-number }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_AUTHKEY: ${{ secrets.APPSTORE_AUTHKEY }}
          CHANGELOG: ${{ steps.changelog.outputs.log }}
