name: Testflight build

on:
  workflow_dispatch:
    inputs:
      buildNumber:
        description: 'Build number'
        required: true

jobs:
  testflight-build:
    name: Create new iOS & Android builds and upload them via Testflight
    runs-on: macos-latest
    environment: fastlane
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare changelog
        id: changelog
        run: echo "##[set-output name=log;]$(git log --pretty=format:'%s' origin/master..origin/$(echo ${GITHUB_REF#refs/heads/}))"

      - name: Install SSH key to get acces to repository with Certificates and Provisioning profiles
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Install Android Gemfile dependencies
        run: cd android && bundle install

      - name: Build Android & Distribute to Google Play Console
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          cd android && ./decrypt_script.sh
          yarn android:test-flight
        env:
          BUILD_NUMBER: ${{ github.event.inputs.buildNumber }}
          READ_ONLY_SIGNER_PUBLIC_KEY: ${{ secrets.READ_ONLY_SIGNER_PUBLIC_KEY }}
          READ_ONLY_SIGNER_PUBLIC_KEY_HASH: ${{ secrets.READ_ONLY_SIGNER_PUBLIC_KEY_HASH }}
          GOOGLE_PLAY_AUTHKEY: ${{ secrets.GOOGLE_PLAY_AUTHKEY }}
          KEYSTORE_KEY: ${{ secrets.KEYSTORE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: Install iOS Gemfile dependencies
        run: cd ios && bundle install

      - name: Install Pods
        run: yarn ios:pods

      - name: Build iOS & Distribute to Testflight
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          cd ios && ./decrypt_script.sh
          yarn ios:test-flight
        env:
          BUILD_NUMBER: ${{ github.event.inputs.buildNumber }}
          READ_ONLY_SIGNER_PUBLIC_KEY: ${{ secrets.READ_ONLY_SIGNER_PUBLIC_KEY }}
          READ_ONLY_SIGNER_PUBLIC_KEY_HASH: ${{ secrets.READ_ONLY_SIGNER_PUBLIC_KEY_HASH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_AUTHKEY: ${{ secrets.APPSTORE_AUTHKEY }}
          CHANGELOG: ${{ steps.changelog.outputs.log }}
